spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3300/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    redisson:
      file: classpath:redisson.yml